/**
 * PDF Generation Utility
 * Handles PDF report generation
 * Note: This is a server-side PDF generator using basic templates
 * For more complex PDFs, consider using a library like PDFKit
 */

/**
 * Generate HTML report for PDF conversion
 * @param {Object} data - Report data
 * @param {Object} options - Generation options
 * @returns {string} HTML content
 */
const generateReportHTML = (data, options = {}) => {
  const { title = 'DataOps Report', type = 'general' } = options;
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });

  let content = '';

  switch (type) {
    case 'daily':
      content = generateDailyReport(data);
      break;
    case 'weekly':
      content = generateWeeklyReport(data);
      break;
    case 'monthly':
      content = generateMonthlyReport(data);
      break;
    case 'records':
      content = generateRecordsReport(data);
      break;
    default:
      content = generateGeneralReport(data);
  }

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      font-size: 12px;
      line-height: 1.5;
      color: #1a202c;
      padding: 40px;
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #1a365d;
    }
    .header h1 {
      font-size: 24px;
      color: #1a365d;
      margin-bottom: 10px;
    }
    .header .subtitle {
      font-size: 14px;
      color: #718096;
    }
    .meta {
      display: flex;
      justify-content: space-between;
      margin-bottom: 30px;
      font-size: 11px;
      color: #718096;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 20px;
      margin-bottom: 30px;
    }
    .stat-card {
      background: #f7fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 15px;
      text-align: center;
    }
    .stat-card .value {
      font-size: 24px;
      font-weight: bold;
      color: #1a365d;
    }
    .stat-card .label {
      font-size: 11px;
      color: #718096;
      margin-top: 5px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
    }
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #e2e8f0;
    }
    th {
      background: #f7fafc;
      font-weight: 600;
      color: #1a365d;
    }
    tr:hover {
      background: #f7fafc;
    }
    .status-pending {
      color: #d69e2e;
    }
    .status-processed {
      color: #38a169;
    }
    .status-discrepancy {
      color: #e53e3e;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      font-size: 10px;
      color: #718096;
    }
    .chart-placeholder {
      background: #f7fafc;
      border: 1px dashed #cbd5e0;
      border-radius: 8px;
      padding: 40px;
      text-align: center;
      color: #718096;
      margin-bottom: 20px;
    }
    @media print {
      body {
        padding: 20px;
      }
      .stat-card {
        break-inside: avoid;
      }
      table {
        break-inside: auto;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <div class="subtitle">DataOps Manager Report</div>
  </div>
  <div class="meta">
    <span>Generated: ${dateStr} at ${timeStr}</span>
    <span>Page 1 of 1</span>
  </div>
  ${content}
  <div class="footer">
    <p>Generated by DataOps Manager</p>
    <p>This report is auto-generated and for internal use only.</p>
  </div>
</body>
</html>
  `;
};

/**
 * Generate daily report content
 */
const generateDailyReport = (data) => {
  const { stats, records } = data;

  return `
    <div class="stats-grid">
      <div class="stat-card">
        <div class="value">${stats.totalRecords || 0}</div>
        <div class="label">Total Records</div>
      </div>
      <div class="stat-card">
        <div class="value">${(stats.totalReceived || 0).toLocaleString()}</div>
        <div class="label">Records Received</div>
      </div>
      <div class="stat-card">
        <div class="value">${(stats.totalProcessed || 0).toLocaleString()}</div>
        <div class="label">Records Processed</div>
      </div>
      <div class="stat-card">
        <div class="value">${(stats.totalPending || 0).toLocaleString()}</div>
        <div class="label">Pending Records</div>
      </div>
      <div class="stat-card">
        <div class="value">${stats.pendingCount || 0}</div>
        <div class="label">Pending Items</div>
      </div>
      <div class="stat-card">
        <div class="value">${stats.discrepancyCount || 0}</div>
        <div class="label">Discrepancies</div>
      </div>
    </div>
    <h2>Daily Records</h2>
    ${records && records.length > 0 ? `
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Unit</th>
            <th>Department</th>
            <th>Category</th>
            <th>Received</th>
            <th>Processed</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${records.map(r => `
            <tr>
              <td>${r.recordId || '-'}</td>
              <td>${r.unit || '-'}</td>
              <td>${r.department?.name || '-'}</td>
              <td>${r.category?.name || '-'}</td>
              <td>${(r.recordsReceived || 0).toLocaleString()}</td>
              <td>${(r.recordsProcessed || 0).toLocaleString()}</td>
              <td class="status-${r.status}">${r.status}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    ` : '<p>No records found for this date.</p>'}
  `;
};

/**
 * Generate weekly report content
 */
const generateWeeklyReport = (data) => {
  const { stats, records } = data;

  return `
    <div class="stats-grid">
      <div class="stat-card">
        <div class="value">${stats.totalRecords || 0}</div>
        <div class="label">Total Records</div>
      </div>
      <div class="stat-card">
        <div class="value">${(stats.totalReceived || 0).toLocaleString()}</div>
        <div class="label">Records Received</div>
      </div>
      <div class="stat-card">
        <div class="value">${(stats.totalProcessed || 0).toLocaleString()}</div>
        <div class="label">Records Processed</div>
      </div>
    </div>
    <h2>Weekly Summary (${stats.weekStart} - ${stats.weekEnd})</h2>
    ${stats.dailyData && stats.dailyData.length > 0 ? `
      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Count</th>
            <th>Received</th>
            <th>Processed</th>
          </tr>
        </thead>
        <tbody>
          ${stats.dailyData.map(d => `
            <tr>
              <td>${d._id}</td>
              <td>${d.count}</td>
              <td>${(d.totalReceived || 0).toLocaleString()}</td>
              <td>${(d.totalProcessed || 0).toLocaleString()}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    ` : '<p>No data available for this week.</p>'}
  `;
};

/**
 * Generate monthly report content
 */
const generateMonthlyReport = (data) => {
  const { stats, records } = data;

  return `
    <div class="stats-grid">
      <div class="stat-card">
        <div class="value">${stats.totalRecords || 0}</div>
        <div class="label">Total Records</div>
      </div>
      <div class="stat-card">
        <div class="value">${(stats.totalReceived || 0).toLocaleString()}</div>
        <div class="label">Records Received</div>
      </div>
      <div class="stat-card">
        <div class="value">${(stats.totalProcessed || 0).toLocaleString()}</div>
        <div class="label">Records Processed</div>
      </div>
    </div>
    <h2>Monthly Summary - ${stats.month}</h2>
    ${stats.departmentBreakdown && stats.departmentBreakdown.length > 0 ? `
      <h3>Department Breakdown</h3>
      <table>
        <thead>
          <tr>
            <th>Department</th>
            <th>Count</th>
            <th>Received</th>
            <th>Processed</th>
          </tr>
        </thead>
        <tbody>
          ${stats.departmentBreakdown.map(d => `
            <tr>
              <td>${d.name}</td>
              <td>${d.count}</td>
              <td>${(d.totalReceived || 0).toLocaleString()}</td>
              <td>${(d.totalProcessed || 0).toLocaleString()}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    ` : '<p>No data available for this month.</p>'}
  `;
};

/**
 * Generate records report content
 */
const generateRecordsReport = (data) => {
  const records = Array.isArray(data) ? data : [];

  return `
    <h2>Records Report</h2>
    <p>Total Records: ${records.length}</p>
    ${records.length > 0 ? `
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Unit</th>
            <th>Department</th>
            <th>Category</th>
            <th>Date</th>
            <th>Received</th>
            <th>Processed</th>
            <th>Pending</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${records.map(r => `
            <tr>
              <td>${r.recordId || '-'}</td>
              <td>${r.unit || '-'}</td>
              <td>${r.department?.name || r.department || '-'}</td>
              <td>${r.category?.name || r.category || '-'}</td>
              <td>${r.date ? new Date(r.date).toLocaleDateString() : '-'}</td>
              <td>${(r.recordsReceived || 0).toLocaleString()}</td>
              <td>${(r.recordsProcessed || 0).toLocaleString()}</td>
              <td>${(r.pendingRecords || 0).toLocaleString()}</td>
              <td class="status-${r.status}">${r.status}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    ` : '<p>No records to display.</p>'}
  `;
};

/**
 * Generate general report content
 */
const generateGeneralReport = (data) => {
  return `
    <h2>Report Data</h2>
    <pre>${JSON.stringify(data, null, 2)}</pre>
  `;
};

/**
 * Generate PDF options for Express response
 * @param {string} filename - Output filename
 * @returns {Object} Response options
 */
const getPDFResponseOptions = (filename = 'report.pdf') => ({
  filename,
  contentType: 'text/html',
  // Note: For actual PDF generation, use a library like PDFKit or puppeteer
  // This returns HTML that can be printed to PDF in the browser
});

module.exports = {
  generateReportHTML,
  getPDFResponseOptions,
};